openapi: 3.0.0
info:
  title: Hello World API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Returns a "Hello World" message
      parameters:
        - in: query
          name: name
          description: The name of the person to greet
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Hello World